apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: n922s4s7r-nodejs 
  janus-idp.io/tekton: n922s4s7r-nodejs
  backstage.io/kubernetes-id: n922s4s7r-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n922s4s7r-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml